// Expose cars as a global so the UI works when opening index.html directly
window.cars = [
  {
    id: "corolla-hybrid",
    brand: "Toyota",
    model: "Corolla Hybrid",
    segment: "Compacto",
    fuel: "hybrid",
    fuelLabel: "Híbrido",
    transmission: "auto",
    transmissionLabel: "Automático",
    price: 26500,
    consumption: 4.5,
    yearlyCost: 1350,
    safetyScore: 9.2,
    economyScore: 9.0,
    comfortScore: 7.8,
    totalScore: 8.6,
    boot: 361,
    tags: ["city", "eco", "family"],
    tagsLabel: "Ciudad • Ahorro • Familiar",
    highlight: "Ideal si buscas fiabilidad y consumos muy bajos en uso diario.",
  },
  {
    id: "megane-diesel",
    brand: "Renault",
    model: "Mégane Blue dCi",
    segment: "Compacto",
    fuel: "diesel",
    fuelLabel: "Diésel",
    transmission: "manual",
    transmissionLabel: "Manual",
    price: 21500,
    consumption: 4.1,
    yearlyCost: 1420,
    safetyScore: 8.4,
    economyScore: 8.7,
    comfortScore: 7.2,
    totalScore: 8.0,
    boot: 434,
    tags: ["city", "eco"],
    tagsLabel: "Ciudad • Ahorro",
    highlight: "Muy eficiente en carretera, buena opción para hacer muchos kilómetros.",
  },
  {
    id: "qashqai-petrol",
    brand: "Nissan",
    model: "Qashqai",
    segment: "SUV compacto",
    fuel: "gasoline",
    fuelLabel: "Gasolina",
    transmission: "auto",
    transmissionLabel: "Automático",
    price: 29500,
    consumption: 6.5,
    yearlyCost: 1750,
    safetyScore: 8.8,
    economyScore: 7.2,
    comfortScore: 8.4,
    totalScore: 8.1,
    boot: 504,
    tags: ["family", "adventure"],
    tagsLabel: "Familiar • Aventura",
    highlight: "Postura elevada y buen espacio interior para familia y viajes.",
  },
  {
    id: "sportage-diesel",
    brand: "Kia",
    model: "Sportage",
    segment: "SUV compacto",
    fuel: "diesel",
    fuelLabel: "Diésel",
    transmission: "auto",
    transmissionLabel: "Automático",
    price: 31500,
    consumption: 5.2,
    yearlyCost: 1680,
    safetyScore: 9.0,
    economyScore: 7.8,
    comfortScore: 8.6,
    totalScore: 8.5,
    boot: 526,
    tags: ["family", "adventure"],
    tagsLabel: "Familiar • Aventura",
    highlight: "Muy equipado de serie, cómodo para viajes largos y con buen maletero.",
  },
  {
    id: "sandero-gpl",
    brand: "Dacia",
    model: "Sandero ECO-G",
    segment: "Utilitario",
    fuel: "gasoline",
    fuelLabel: "Gasolina / GLP",
    transmission: "manual",
    transmissionLabel: "Manual",
    price: 13500,
    consumption: 6.3,
    yearlyCost: 1100,
    safetyScore: 6.8,
    economyScore: 8.8,
    comfortScore: 6.9,
    totalScore: 7.4,
    boot: 328,
    tags: ["city", "eco"],
    tagsLabel: "Ciudad • Ahorro",
    highlight: "Opción muy económica con buenos costes por kilómetro con GLP.",
  },
  {
    id: "id3-electric",
    brand: "Volkswagen",
    model: "ID.3",
    segment: "Compacto eléctrico",
    fuel: "electric",
    fuelLabel: "Eléctrico",
    transmission: "auto",
    transmissionLabel: "Automático",
    price: 36000,
    consumption: 16,
    yearlyCost: 980,
    safetyScore: 9.0,
    economyScore: 9.2,
    comfortScore: 8.2,
    totalScore: 8.7,
    boot: 385,
    tags: ["city", "eco"],
    tagsLabel: "Ciudad • Ahorro",
    highlight: "Cero emisiones en uso y muy suave en ciudad, con buena autonomía.",
  },
  {
    id: "cx5-petrol",
    brand: "Mazda",
    model: "CX-5",
    segment: "SUV mediano",
    fuel: "gasoline",
    fuelLabel: "Gasolina",
    transmission: "auto",
    transmissionLabel: "Automático",
    price: 34000,
    consumption: 7.1,
    yearlyCost: 1890,
    safetyScore: 9.1,
    economyScore: 7.0,
    comfortScore: 8.9,
    totalScore: 8.4,
    boot: 506,
    tags: ["family", "adventure"],
    tagsLabel: "Familiar • Aventura",
    highlight: "Excelente confort de marcha y acabados interiores de alta calidad.",
  },
  {
    id: "yaris-hybrid",
    brand: "Toyota",
    model: "Yaris Hybrid",
    segment: "Utilitario",
    fuel: "hybrid",
    fuelLabel: "Híbrido",
    transmission: "auto",
    transmissionLabel: "Automático",
    price: 20500,
    consumption: 3.9,
    yearlyCost: 1150,
    safetyScore: 8.7,
    economyScore: 9.3,
    comfortScore: 7.0,
    totalScore: 8.3,
    boot: 286,
    tags: ["city", "eco"],
    tagsLabel: "Ciudad • Ahorro",
    highlight: "Muy ágil y eficiente en ciudad, perfecto si aparcas a menudo.",
  },
  {
    id: "leon-petrol",
    brand: "SEAT",
    model: "León",
    segment: "Compacto",
    fuel: "gasoline",
    fuelLabel: "Gasolina",
    transmission: "manual",
    transmissionLabel: "Manual",
    price: 22800,
    consumption: 5.8,
    yearlyCost: 1450,
    safetyScore: 8.2,
    economyScore: 7.9,
    comfortScore: 7.5,
    totalScore: 7.9,
    boot: 380,
    tags: ["city", "family"],
    tagsLabel: "Ciudad • Familiar",
    highlight: "Buena relación precio/prestaciones, apto tanto para ciudad como viajes.",
  },
  {
    id: "model3-rwd",
    brand: "Tesla",
    model: "Model 3 RWD",
    segment: "Berlina eléctrica",
    fuel: "electric",
    fuelLabel: "Eléctrico",
    transmission: "auto",
    transmissionLabel: "Automático",
    price: 39900,
    consumption: 14,
    yearlyCost: 900,
    safetyScore: 9.5,
    economyScore: 9.0,
    comfortScore: 8.4,
    totalScore: 9.0,
    boot: 561,
    tags: ["city", "eco", "adventure"],
    tagsLabel: "Ciudad • Ahorro • Aventura",
    highlight: "Muy buena autonomía y prestaciones, ideal si puedes cargar en casa.",
  },
];

// For environments that support ES modules, also export for compatibility
try {
  // define an immutable export-like property (no-op in browsers without module loader)
  Object.defineProperty(window, 'exports', { value: window.exports || {}, configurable: true });
} catch (e) {
  // ignore
}